# Version Snapshot 1.0.0


# LOGO


Debug: false

# Need to put this plugin in your Spigot/Bukkit server 
spigot-sync: false

DataStore:

  # MySQL or File
  Type: "MySQL"
  
  MySQL:
    Host: localhost
    User: "root"
    Password: ""
    Database: "BungeeGroups"
    Port: 3306
    
    TimeOut: 3

